name: CI/CD of basic-nodejs-s2

on:
  push:
    branches: [ "main" ]

jobs:

  build-and-push:
    
    runs-on: ubuntu-latest
   
    steps:
    
      - name: Clone code from github
        uses: actions/checkout@v4

      - name: show source code
        run: ls