name: CI/CD of basic-nodejs-s2

on:
  push:
    branches: [ "main" ]

jobs:

  job-1:
    
    runs-on: ubuntu-latest
   
    steps:
    
      - name: step-1
        run: echo step-1/job-1

  job-2-1:

    needs: ["job-1"]

    runs-on: ubuntu-latest
   
    steps:
    
      - name: step-1
        run: echo step-1/job-2

  job-2-2:

    needs: ["job-1"]

    runs-on: ubuntu-latest
    
    steps:
    
      - name: step-1
        run: echo step-1/job-2
      
  job-3:

    needs: ["job-2-1","job-2-2"]

    runs-on: ubuntu-latest
   
    steps:
    
      - name: step-1
        run: echo step-1/job-3