name: CI/CD of basic-nodejs-s2

on:
  push:
    branches: [ "main" ]

jobs:

  job-1:
    
    runs-on: ubuntu-latest
   
    steps:
    
      - name: step-1
        run: echo step-1/job-1

    
      - name: step-1
        run: echo step-1/job-3