name: CI/CD of basic-nodejs-s2

on:
  push:
    branches: [ "main" ]


env:
  BUILD_NUMBER: ${{ github.run_number }}

jobs:

  build-and-push:
    
    runs-on: ubuntu-latest
   
    steps:
    
      - name: Clone code from github
        uses: actions/checkout@v4

      - name: build docker image
        run: docker build -t basic-nodejs-s2-image:${{ env.BUILD_NUMBER }} .
      
      - name: tag docker image
        run: docker tag basic-nodejs-s2-image:${{ env.BUILD_NUMBER }} ${{ secrets.DOCKERHUB_USERNAME }}/basic-nodejs-s2-image:${{ env.BUILD_NUMBER }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push docker image to docker hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/basic-nodejs-s2-image:${{ env.BUILD_NUMBER }} 


  test:

      needs: ["build-and-push"]

      runs-on: ubuntu-latest

      steps:
    
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: pull image
          run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/basic-nodejs-s2-image:${{ env.BUILD_NUMBER }}
        
        - name: run unit test
          run: docker run ${{ secrets.DOCKERHUB_USERNAME }}/basic-nodejs-s2-image:${{ env.BUILD_NUMBER }} npm test


  deploy:

        needs: ["test"]


        runs-on: ubuntu-latest

        steps:


          - name: connect to the VPS using SSH.
            uses: appleboy/ssh-action@master
            with:
              host: ${{ secrets.VPS_HOST }}
              username: ${{ secrets.VPS_USERNAME }}
              password:  ${{ secrets.VPS_PASSWORD }}
    
              script: | 

                  sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/basic-nodejs-s2-image:${{ env.BUILD_NUMBER }}
                  sudo docker stop basic-nodejs-s2-container 
                  sudo docker rm basic-nodejs-s2-container 
                  sudo docker run -d -p 3003:3000 --name basic-nodejs-s2-container  ${{ secrets.DOCKERHUB_USERNAME }}/basic-nodejs-s2-image:${{ env.BUILD_NUMBER }}


  health_check:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Wait for service to start
        run: sleep 10s 

      - name: Test Health Check
        run: |
          curl https://session-2.lebondeveloppeur.net/health || exit 1 # Fail the job if health check fails