name: CI/CD of basic-nodejs-s2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-job:

    runs-on: ubuntu-latest
   
    steps:
     
      - name: Clone code in the current folder
        uses: actions/checkout@v4
    
      - name: show source code
        run: ls

      - name: show message in the runner terminal
        run: echo Hello, chabeb !
